name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            ocaml-compiler: 5.2.1
          - os: macos-13
            arch: x64
            ocaml-compiler: 5.2.1
          - os: macos-14
            arch: arm64
            ocaml-compiler: 5.2.1
          - os: windows-latest
            arch: x64
            ocaml-compiler: 5.2.1

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          opam-disable-sandboxing: true

      - name: Install deps
        run: make install

      - name: Install npm deps
        run: make npm-install

      - name: Pin some deps
        run: make pin

      - name: Build
        run: make build-prod

      - name: Run tests
        run: make test

      - name: Upload artifacts for ${{ matrix.os }}-${{ matrix.arch }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-artifact
          path: _build/default/bin/bin.exe

      - name: Upload JavaScript artifacts for NPM
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: query-json-js
          path: _build/default/js/js.bc.js
