name: Website

on:
  push:
    branches: [main]
  pull_request:

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    needs: []

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Use OCaml 5.2.1
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.1
          dune-cache: true
          opam-disable-sandboxing: true

      - name: Install deps
        run: make install

      - name: Install npm deps
        run: make npm-install

      - name: Pin some deps
        run: make pin

      - name: Build
        run: make build-prod

      - name: Build website
        run: make web-build

      - name: Deploy to prod
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        working-directory: ./website
        env:
          SITE_ID: ${{ secrets.SITE_ID }}
          AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: npx netlify deploy --site $SITE_ID --auth $AUTH_TOKEN --prod --dir=../dist

      - name: Deploy preview
        if: ${{ github.event_name == 'pull_request' }}
        working-directory: ./website
        env:
          SITE_ID: ${{ secrets.SITE_ID }}
          AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: npx netlify deploy --site $SITE_ID --auth $AUTH_TOKEN --dir=../dist

